In [1]:
import pandas as pd
from sqlalchemy import create_engine
from dotenv import load_dotenv
import os
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression# pattern
from sklearn.ensemble import RandomForestClassifier

In [2]:
engine = create_engine(os.getenv("DB_URL"))

In [3]:
df = pd.read_sql('select * from ballon_dor.ballon_dor_features', engine)
df.shape

(438, 14)

In [4]:
train = df[df.final_rank.notna()].copy()
test = df[df.final_rank.isna()].copy()

train.shape, test.shape

((408, 14), (30, 14))

In [5]:
train["is_winner"] = (train["final_rank"] == 1).astype(int)

In [6]:
train["has_stats"] = train["goals"].notna().astype(int)
train["has_stats"].value_counts()

has_stats
1    396
0     12
Name: count, dtype: int64

In [7]:
median_goals = train["goals"].median()      # median ignores NaN by default
train["goals"] = train["goals"].fillna(median_goals)

median_minutes = train["minutes"].median()
train["minutes"] = train["minutes"].fillna(median_minutes)

median_assists = train["assists"].median()
train["assists"] = train["assists"].fillna(median_assists)

In [8]:
test["has_stats"] = test["goals"].notna().astype(int)
test["has_stats"].value_counts()

has_stats
1    27
0     3
Name: count, dtype: int64

In [9]:
test["goals"] = test["goals"].fillna(median_goals)
test["minutes"] = test["minutes"].fillna(median_minutes)
test["assists"] = test["assists"].fillna(median_assists)

In [10]:
test[["goals","assists","minutes"]].isna().sum()

goals      0
assists    0
minutes    0
dtype: int64

In [11]:
train

,season,player_name,main_club,final_rank,won_league,ucl_stage,club,minutes,goals,assists,main_position,nation,tournament,intl_stage,is_winner,has_stats
0,2010,Andrés Iniesta,Barcelona,2.0,1,4,Barcelona,1905.0,1.0,3.0,MF,ESP,WC,6,0,1
1,2010,Arjen Robben,Bayern Munich,14.0,1,5,Bayern Munich,1778.0,16.0,5.0,FW,NED,WC,5,0,1
2,2010,Asamoah Gyan,Sunderland,18.0,0,0,Rennes,2079.0,13.0,2.0,FW,GHA,WC,3,0,1
3,2010,Bastian Schweinsteiger,Bayern Munich,16.0,1,5,Bayern Munich,2903.0,2.0,2.0,DF,GER,WC,4,0,1
4,2010,Carles Puyol,Barcelona,11.0,1,4,Barcelona,2712.0,1.0,1.0,DF,ESP,WC,6,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403,2025,Serhou Guirassy,Borussia Dortmund,21.0,0,3,Dortmund,2598.0,21.0,4.0,FW,GUI,None,0,0,1
404,2025,Viktor Gyökeres,Sporting CP,15.0,0,1,None,2606.0,10.0,6.0,None,SWE,None,0,0,0
405,2025,Vinicius Júnior,Real Madrid,16.0,0,3,Real Madrid,2253.0,11.0,8.0,FW,BRA,None,0,0,1
406,2025,Virgil van Dijk,Liverpool,28.0,1,2,Liverpool,3330.0,3.0,1.0,DF,NED,None,0,0,1
407,2025,Vitinha,Paris Saint-Germain,3.0,1,6,Paris SG,2042.0,5.0,1.0,MF,POR,None,0,0,1

In [12]:
features = ["goals", "assists", "minutes", "ucl_stage", "intl_stage", "won_league", "has_stats"]

X_train = pd.get_dummies(train[features + ["main_position"]], columns=["main_position"], drop_first=True)
X_test  = pd.get_dummies(test[features + ["main_position"]],  columns=["main_position"], drop_first=True)
X_test  = X_test.reindex(columns=X_train.columns, fill_value=0)

y_train = train["is_winner"]

In [13]:
train["is_winner"].value_counts(),

(is_winner
 0    393
 1     15
 Name: count, dtype: int64,)

In [14]:
model = RandomForestClassifier(n_estimators=200, class_weight="balanced", random_state=1)

In [15]:
model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', n_estimators=200,
                       random_state=1)

In [16]:
proba = model.predict_proba(X_test)[:,1]
proba

array([0.005, 0.005, 0.   , 0.005, 0.005, 0.03 , 0.035, 0.   , 0.05 ,
       0.   , 0.   , 0.   , 0.02 , 0.01 , 0.115, 0.005, 0.01 , 0.   ,
       0.005, 0.   , 0.02 , 0.   , 0.03 , 0.015, 0.005, 0.   , 0.   ,
       0.015, 0.   , 0.   ])

In [22]:
ranking = test[["player_name", "main_club"]].copy()
ranking["proba"] = proba
ranking.sort_values("proba", ascending=False).head(10)

               player_name            main_club  proba
422           Lamine Yamal            Barcelona  0.115
416             Harry Kane        Bayern Munich  0.050
414          Ferran Torres            Barcelona  0.035
413       Fabián Ruiz Peña  Paris Saint-Germain  0.030
430        Ousmane Dembélé  Paris Saint-Germain  0.030
428          Michael Olise        Bayern Munich  0.020
420  Khvicha Kvaratskhelia  Paris Saint-Germain  0.020
435                Vitinha  Paris Saint-Germain  0.015
431            Pau Cubarsí            Barcelona  0.015
424           Lionel Messi          Inter Miami  0.010

In [23]:
ranking.to_csv("../data/predictions_2026.csv", index=False)

In [26]:
winners = []

for seed in range(1000):
    model = RandomForestClassifier(n_estimators=200, class_weight="balanced", random_state=seed)
    model.fit(X_train, y_train)
    p = model.predict_proba(X_test)[:,1]
    position = p.argmax()
    top = test["player_name"].iloc[position]
    winners.append(top)

In [28]:
pd.Series(winners).value_counts().to_csv("../data/mc_top_counts_2026.csv")